name: Restart Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/lucian/Arch0
            git pull
            docker stop arch0-bot || true
            docker rm arch0-bot || true
            docker build -t arch0 .
            docker run -d --restart unless-stopped --name arch0-bot arch0

      - name: Recovery: force checkout and retry
        if: failure()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /home/lucian/Arch0
            git reset --hard HEAD
            git clean -fd
            git pull
            docker stop arch0-bot || true
            docker rm arch0-bot || true
            docker build -t arch0 .
<<<<<<< HEAD
            docker run -d --restart unless-stopped --name arch0-bot arch0
=======
            docker run -d --restart unless-stopped --name arch0-bot arch0
>>>>>>> 9f05282c572e05bbffa8daac65e24ee3b939e2b5
